---

- name: create user
  hosts: webservers
  become: true
  become_method: sudo

  tasks:
     - name: create users
       user:
          name: "{{ item }}"
          state: present
       with_items:
          - Darsh
          - Kashish
          - Mohit  

