---

- name: creation of linux group
  hosts: webservers
  become: true
  become_method: sudo

  tasks:
      - name: Create groups
        group:
             name: "{{ item }}"
             state: present    
        with_items:
             - QA
             - Development
             - Devops      
