---

- name: Install dependencies
  hosts: webservers
  become: true
  become_method: sudo

  tasks:

    - name: install a list of  packages
      apt:
         name: "{{ item }}"
         state: latest
      with_items:
            - apache2
            - stress 
            - wget
            - nodejs
            - npm
            - docker.io  
